services:
  # --- APLIKASI NODE.JS ---
  node-react:
    build:
      context: ./frontend
    image: react-frontend:latest
    container_name: react-service
    ports:
      - "3000:3000"

  # --- APLIKASI GO ---
  go-api:
    build:
      context: ./go
    image: go-api:latest
    container_name: go-service
    ports:
      - "8080:8080"

  # --- APLIKASI LARAVEL ---
  laravel-app:
    build:
      context: ./laravel
    image: laravel-api:latest
    container_name: laravel-service
    ports:
      - "8001:8001"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=192.168.56.202
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=123
      - APP_ENV=local
      - APP_DEBUG=true
